# properties ??? ?? yml ???? ??.

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true


# H2 DB ?? ??? ??? ? ? ???? ????. (??? ????)

# datasource
# ???? ?? ????? ???? h2 console?? ?? ??? ???? ????.
# (???? ????? ???? ???? ??????.)

# h2 console enabled true
# h2 ??? ?????? ?? ??? ? ?? ??? ??.
# h2 DB? ??????? ??? 8080 ??? ???? ??.
# h2-console ??? ???? ??? ??? ? ?? ?? ??
# http://localhost:8080/h2-console
# JDBC URL? spring datasource url??? ??? jdbc:h2:mem:test? ???? ??? ??? ????.

# defer-datasource-initialization
# true ?? ??? ??? ??? ? ??? ?? ??.
# ? ??? ??? ??? ?? ?? ?? ??? ??? ????? ?.
# ????? 2.5.0???? ??? ??.

# hibernate: ddl-auto: create-drop
# ?????? ?? ??? ??? ?? ??. ????? ??? ?? ??.
# ???? ?? ????.

